# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20161019_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calc',
            old_name='operation',
            new_name='operator',
        ),
    ]
