# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20161019_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calc',
            old_name='results',
            new_name='result',
        ),
    ]
