# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_remove_calc_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calc',
            new_name='Operation',
        ),
    ]
